# Generated by Django 5.1.7 on 2025-04-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='members',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='members',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
    ]
