# Generated by Django 5.1.7 on 2025-05-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_useradress_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradress',
            name='state',
        ),
    ]
